### ISSUE TITLE
Tautulli-Docker can't handle a non-standard http_port

### ISSUE THREAD

**Issue by urda** [Tautulli/Tautulli-Docker#26]
Consider the following (pulled from `source` at time issue of writing):

https://github.com/Tautulli/Tautulli-Docker/blob/a498f3e8a098b3b3234f17b57f533d618b8adb34/Dockerfile#L79-L80

Consider any of the following possible scenarios:

- If you can't have port `8181` in your environment.
- You have multiple `tautulli` docker instances running on the same `eth` interface.
- You redirect external ports to internal `docker` ports that are not a 1-to-1 relationship.

It won't matter if a user updates their `config` to point `http_port` because the health check doesn't account for a possible port change.

## Considered solution:

The port should be determined from a `docker` environment variable, allowing users to re-assign this port. The `tautulli` docker image needs to handle updating it's config and health check to account for this.

**Comment by Arcanemagus** [comment]
That's not how networking works in Docker. The `EXPOSE` directive is a _default_ port to use on the host. Docker lets you publish any port on the host that you want, and still have it directed to the internal port in the container.

[Docker Container Networking](https://docs.docker.com/config/containers/container-networking/)

| Container | Container Port | Host Port |
|---|---|---|
| Tautulli | 8181 | 9191 |
| Other 1 | 8181 | 8181 |
| Other 2 | 8181 | 43210 |

**Do not** try to change the Tautulli port _within_ the container, there is a reason we disable that in the UI when running in Docker.

**Comment by urda** [comment]
I'll need to investigate why the health check is failing then within its container on my end on a different port which lead to this issue, it's acting like localhost within the container didn't respond to 8181, regardless of external port mapping. The original thought that maybe the hard-coded `http_port` was a possible issue.

> That's not how networking works in Docker.

To be more specific that's how your container works here. Nothing I entered in my original comment was wrong about networking in docker, this also includes the concept of updating. Plenty of other containers allow for port changes for whatever reason.

Avoid language like that when responding to someone who has taken the time to fire up a GitHub issue. Especially when that someone has not only contributed to `docker-compose` before, but might also be a Software Engineer over at Amazon.com

**Comment by Arcanemagus** [comment]
> To be more specific that's how your container works here.
> Plenty of other containers allow for port changes for whatever reason.

Very true. We haven't seen a _reason_ for this though, since it's our opinion this should be handled in Docker as the _entire point_ of Docker is to provide an isolated environment for the application, letting the container deal with running the application and Docker handle the host side of things.

If you have a good reason for implementing this it can certainly be done, however nothing you have said so far would fall into this unless I'm mistaken.

> Nothing I entered in my original comment was wrong about networking in docker

This isn't entirely true, or at least the assumptions you are drawing from it aren't valid.

> If you can't have port 8181 in your environment.

As stated, if you can't have port `8181` in your environment then you should be mapping it to a different port on the host.

> You have multiple tautulli docker instances running on the same eth interface.

Again, not correct. I explained above how to handle this.

> You redirect external ports to internal docker ports that are not a 1-to-1 relationship.

If you are talking about what I _think_ you are here (multiple host ports redirecting to the same container port), then I'm not sure what that has to do with the container in the first place, or how being able to change the port within the container would be involved with that in the first place.

----

> Avoid language like that when responding to someone
> Especially when that someone has not only contributed to docker-compose before, but might also be a Software Engineer over at Amazon.com

I'm sorry, I gave the simplistic answer assuming you were just getting started with Docker like many of our users and didn't know about some of the more esoteric edge cases from the incorrect points you laid out in your issue.

I definitely could have worded it better and will keep that in mind 😉.

**Comment by urda** [comment]
> Very true. We haven't seen a reason for this though, since it's our opinion this should be handled in Docker as the entire point of Docker is to provide an isolated environment for the application, letting the container deal with running the application and Docker handle the host side of things.

Correct, but in some scenarios that port exposure is not always up to the Dockerfile itself.

> If you are talking about what I think you are here (multiple host ports redirecting to the same container port), then I'm not sure what that has to do with the container in the first place, or how being able to change the port within the container would be involved with that in the first place.

As in not 1-1 as in you may have an already existing, public service running on 8181.

> I definitely could have worded it better and will keep that in mind.

As you could have, and you should have. Each GitHub issue interaction you have is an opportunity for you to learn about your customers and the possibility of gaining contributors.

Don't make assumptions.

---

I deployed my same container to a new host this morning and was unable to reproduce the health check issue regardless of port mapping. This requires a deep dive on the docker engine side for me. I'll open any related issues if necessary.
